# Generated by Django 4.0.5 on 2022-06-20 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='color',
        ),
    ]
